version: "3.7"
services:
  crafty:
    image: registry.gitlab.com/crafty-controller/crafty-4:latest
    container_name: crafty
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - crafty_data:/crafty

volumes:
  crafty_data:
  
